#import <Foundation/Foundation.h>
#import <CoreBluetooth/CoreBluetooth.h>
#import "bridge.h"
#include "_cgo_export.h" // Auto-generated by Go to call Go functions from C

@interface SnifferDelegate : NSObject <CBCentralManagerDelegate>
@property (nonatomic, strong) CBCentralManager *centralManager;
@end

@implementation SnifferDelegate

- (instancetype)init {
    self =[super init];
    if (self) {
        // Init CBCentralManager without UI popups if possible, running on main queue
        self.centralManager = [[CBCentralManager alloc] initWithDelegate:self queue:nil];
    }
    return self;
}

- (void)centralManagerDidUpdateState:(CBCentralManager *)central {
    if (central.state == CBManagerStatePoweredOn) {
        NSLog(@"[Sniffer] BLE Radio Active. Engaging passive scan...");
        // Allow duplicates to track RSSI fluctuations over time
        NSDictionary *options = @{CBCentralManagerScanOptionAllowDuplicatesKey: @YES};[self.centralManager scanForPeripheralsWithServices:nil options:options];
    } else {
        NSLog(@"[Sniffer] BLE Radio not available. State: %ld", (long)central.state);
    }
}

- (void)centralManager:(CBCentralManager *)central 
 didDiscoverPeripheral:(CBPeripheral *)peripheral 
     advertisementData:(NSDictionary<NSString *,id> *)advertisementData 
                  RSSI:(NSNumber *)RSSI {
    
    // Pass raw UUID string and RSSI to Go for immediate hashing
    const char *uuidStr = [[peripheral.identifier UUIDString] UTF8String];
    ReportDevice((char *)uuidStr, [RSSI intValue]);
}
@end

void startBLEScan(void) {
    @autoreleasepool {
        SnifferDelegate *delegate = [[SnifferDelegate alloc] init];
        // Keep the runloop alive to continue scanning passively
        [[NSRunLoop currentRunLoop] run];
    }
}